import { createHash } from 'node:crypto'
import { defineConfig, type Plugin } from 'vite'

/**
 * Vite stamps `crossorigin` on the emitted <script> and <link rel=stylesheet>.
 * Every asset here is same-origin, so it buys nothing — but it does make the
 * browser send an `Origin` header, and some static hosts (Cloudflare Pages
 * among them) answer that CORS variant with the SPA fallback HTML instead of
 * the file. The stylesheet is then refused for having a `text/html` MIME type
 * and the whole site renders unstyled, while curl (no Origin) sees a perfectly
 * good text/css. Dropping the attribute keeps the request simple.
 */
function noCrossorigin(): Plugin {
  return {
    name: 'no-crossorigin-on-same-origin-assets',
    enforce: 'post',
    transformIndexHtml(html) {
      return html.replace(/\s+crossorigin(=("|')[^"']*\2)?/g, '')
    },
  }
}

/**
 * Writes the service worker, with the precache list filled in from what the
 * build actually emitted.
 *
 * The list has to be generated because Vite hashes asset filenames — a
 * hand-written one goes stale on the next build and the app quietly serves last
 * week's JavaScript forever. Rather than take on Workbox for fifty lines of
 * cache handling, the worker is written out here with the manifest inlined and
 * the build hash as its cache name.
 *
 * What is cached and why:
 *   app shell + data   precache. It is ~1 MB all in and it is the whole app, so
 *                      there is no point being clever about which parts.
 *   aerial tiles       runtime, capped. Third-party, unbounded, and the map is
 *                      still usable without them, so they must never be allowed
 *                      to fill the origin's quota.
 */
function serviceWorker(): Plugin {
  let base = '/'
  return {
    name: 'service-worker',
    apply: 'build',
    configResolved(cfg) { base = cfg.base },
    generateBundle(_opts, bundle) {
      const assets = Object.keys(bundle).map((f) => base + f)
      // public/ files are copied straight through and never appear in the
      // bundle, so they are listed by name.
      const statics = [
        base,
        base + 'manifest.webmanifest',
        base + 'icon-192.png',
        base + 'icon-512.png',
        base + 'icon-maskable-512.png',
        base + 'apple-touch-icon.png',
        base + 'data/campus.json',
        base + 'data/geo.json',
        base + 'font/Noto Sans Regular/0-255.pbf',
        base + 'font/Noto Sans Regular/256-511.pbf',
      ]
      const precache = [...new Set([...statics, ...assets])]
      // Cache name carries a hash of the list, so any change to any asset
      // produces a new cache and the old one is dropped on activate.
      const version = createHash('sha256').update(precache.join('|')).digest('hex').slice(0, 12)

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: swSource(precache, version, base),
      })
    },
  }
}

function swSource(precache: string[], version: string, base: string) {
  return `// Generated by vite.config.ts — do not edit. Rebuild to regenerate.
const CACHE = 'iiest-map-${version}'
const PRECACHE = ${JSON.stringify(precache, null, 2)}
const TILE_CACHE = 'iiest-tiles-v1'
const TILE_LIMIT = 400

self.addEventListener('install', (e) => {
  // \`reload\` so installing never picks a stale copy out of the HTTP cache.
  e.waitUntil(caches.open(CACHE)
    .then((c) => c.addAll(PRECACHE.map((u) => new Request(u, { cache: 'reload' }))))
    .then(() => self.skipWaiting()))
})

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) {
      if (k !== CACHE && k !== TILE_CACHE) await caches.delete(k)
    }
    await self.clients.claim()
  })())
})

let lastNotified = 0
async function notifyUnreachable() {
  // One message every few seconds at most: a viewport of tiles fails all at
  // once, and the page only needs telling the first time.
  const now = Date.now()
  if (now - lastNotified < 5000) return
  lastNotified = now
  for (const client of await self.clients.matchAll({ type: 'window' })) {
    client.postMessage({ type: 'imagery-unreachable' })
  }
}

// Keep the tile cache from growing without limit: it is third-party imagery and
// there is no natural end to it.
async function trimTiles(cache) {
  const keys = await cache.keys()
  if (keys.length <= TILE_LIMIT) return
  for (const k of keys.slice(0, keys.length - TILE_LIMIT)) await cache.delete(k)
}

self.addEventListener('fetch', (e) => {
  const { request } = e
  if (request.method !== 'GET') return
  const url = new URL(request.url)

  // Aerial tiles: serve from cache when it has them, otherwise fetch and keep a
  // bounded number. Offline this simply misses, which is what the app expects.
  if (url.hostname.endsWith('arcgisonline.com')) {
    e.respondWith((async () => {
      const cache = await caches.open(TILE_CACHE)
      const hit = await cache.match(request)
      if (hit) return hit
      try {
        const res = await fetch(request)
        if (res.ok) { await cache.put(request, res.clone()); trimTiles(cache) }
        return res
      } catch {
        // MapLibre ignores a failed raster tile silently — no error event, no
        // console entry — so the page has no way to notice on its own. Tell it,
        // throttled, so it can fall back to the drawn map.
        notifyUnreachable()
        return new Response('', { status: 504, statusText: 'offline' })
      }
    })())
    return
  }

  if (url.origin !== self.location.origin) return

  // Navigations: serve the shell from cache first so a cold start offline still
  // opens, and refresh it in the background when there is a network.
  if (request.mode === 'navigate') {
    e.respondWith((async () => {
      const cache = await caches.open(CACHE)
      const shell = await cache.match('${base}')
      const fresh = fetch(request).then((res) => {
        if (res.ok) cache.put('${base}', res.clone())
        return res
      }).catch(() => null)
      return shell ?? (await fresh) ?? new Response('offline', { status: 503 })
    })())
    return
  }

  // Everything else the app owns: cache first. Filenames are content-hashed, so
  // a cache hit is never the wrong version.
  e.respondWith((async () => {
    const cache = await caches.open(CACHE)
    const hit = await cache.match(request)
    if (hit) return hit
    try {
      const res = await fetch(request)
      if (res.ok && new URL(request.url).origin === self.location.origin) {
        cache.put(request, res.clone())
      }
      return res
    } catch (err) {
      throw err
    }
  })())
})
`
}

export default defineConfig({
  plugins: [noCrossorigin(), serviceWorker()],
  /**
   * GitHub Pages serves a project site from `/<repo>/`, not from the domain
   * root, and every asset URL has to agree — get this wrong and the page loads
   * to a blank screen with four 404s. The deploy workflow works the path out
   * from the repository name and passes it in, so nothing is hard-coded here
   * and `npm run dev` still runs at `/`.
   */
  base: process.env.BASE_PATH || '/',
  server: { port: 5180, open: false },
  build: { target: 'es2022', chunkSizeWarningLimit: 1200 },
})
